import React from "react";
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
export default function myHead(){
    return(
        <>
        <Head>
            <title>Thao tác với thẻ Head</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className = {styles.componentCenter}>
            <div>
            <h1> Thiết lập title, meta, link </h1>
            <p>Để thao tác bên trong thẻ head bằng các thẻ như title, meta, link, 
                chúng ta ko thể code trong thẻ head như trong html mà chúng ta phải sử dụng
                Head với chữ H viết hoa
                Chúng ta cũng phải import Head từ next/head để có thể dùng được thẻ Head này.
            </p>
        </div>
        <div className ={styles.linkbutton}>
            <Link href='/'>
                <a >
                    <h2>Bấm vào đây để về Home Page &rarr;</h2>
                    <p>
                    Nút này dùng thẻ a lồng trong thẻ Link
                    </p>
                </a>
            </Link>
            </div>
        </div>
        </>
    )
}