import React from "react";
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import Head from 'next/head';
import styles2 from '../styles/Button.module.css';
export default function tut_css(){
    return(
        <>
        <Head>
            <title>Học về CSS trong NextJS</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className = {styles.componentCenter}>
            <div>
                <h1> CSS trong NextJS</h1>
                <p>-File _app.js là file sẽ xuất ra tất cả các pages, import 1 file style vào _app.js 
                    thì style đó sẽ áp dụng cho tất cả các page. {'(Global file)'}
                </p>
                <p>
                    -Khi có 1 thành phần {'(module)'} được dùng đi dùng lại nhiều lần, chúng ta có thể
                    tạo 1 style cho module đó. Thí dụ chúng ta có button được dùng nhiều lần trong app,
                     ta có thể style cho button này trong file Button.module.css.
                     
                </p>
                <p>
                        Nhớ khai báo className của button: {'(className = {style.button }'}
                </p>
                <p>
                    SaSS support - chưa tìm hiểu
                </p>
                <p>
                    Style trực tiếp trong file .js:
                </p>
                <p>
                    Chúng ta có thể style cho các thành phần ngay trong file js đó bằng jsx {'(<style jsx>)'}
                    Ví dụ:
                           {'<style jsx>{` p { color: blue;} `}</style>'}                            
                </p>

            </div>
        <div className ={styles.linkbutton}>
            <Link href='https://nextjs.org/docs/basic-features/built-in-css-support'>
                <a >
                    <h2>Bấm vào đây để học css &rarr;</h2>
                    <p>
                    Nút này dùng thẻ a lồng trong thẻ Link
                    </p>
                </a>
            </Link>
        </div>
        <Link  href="/">
        <a className={styles.button}>
            BACK
        </a >
        </Link>
        </div>
        </>
    )
}